name: Build BookForge Pro

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir pyinstaller
      - name: Lint
        run: python -m py_compile bookforge_core.py cli_app.py gui_app.py gui_app_main.py build_app.py client_config.py

      - name: Build Windows EXE
        run: |
          cd ${{ github.workspace }}
          pyinstaller --onefile --icon=${{ github.workspace }}/assets/icon.ico ${{ github.workspace }}/gui_app.py --name BookForgePro

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: BookForgePro-Windows
          path: dist/BookForgePro.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          python3 -m pip install --upgrade pip
          pip3 install --no-cache-dir -r requirements.txt
          pip3 install --no-cache-dir pyinstaller
      - name: Lint
        run: python3 -m py_compile bookforge_core.py cli_app.py gui_app.py gui_app_main.py build_app.py client_config.py

      - name: Build macOS App
        run: |
          cd ${{ github.workspace }}
          pyinstaller --onefile --windowed --icon=${{ github.workspace }}/assets/icon.icns ${{ github.workspace }}/gui_app.py --name BookForgePro

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: BookForgePro-macOS
          path: dist/BookForgePro
