name: Build BookForge Pro

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build Windows EXE
        run: |
          pyinstaller --onefile --icon=assets/icon.ico gui_app.py --name BookForgePro
      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/BookForgePro.exe

  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build MacOS App
        run: |
          pyinstaller --onefile --icon=assets/icon.icns gui_app.py --name BookForgePro
      - name: Upload Mac Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: dist/BookForgePro
